dependencies:
  - Carthage/*
  - Gemfile

enhancement:
  - Sources/*
  - Tests/*

CI/CD:
  - fastlane/*
  - travis.yml
  - Dangerfile
  - .circleci/*
  - .ruby-version
  - .swift-version
  - Makefile
