version: 2

defaults: &defaults
  working_directory: /Users/distiller/peril-settings
  shell: /bin/bash --login -o pipefail
  environment:
    CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    LC_ALL: en_US.UTF-8

jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: yarn install
          command: 'yarn install'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command:
            - yarn type-check
            - yarn jest
      # - run:
      #     name: code-coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
      # - store_test_results:
      #     path: test-results.xml

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: yarn install
          command: 'yarn install'
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command:
            - yarn type-check
            - yarn jest

workflows:
  version: 2
  build-and-test:
    jobs:
    - test
