version: 2.1
orbs:
  node: circleci/node@1.1

defaults: &defaults
  executor: node/default

default_parameters: &default_parameters
  post_install:
    description: Custom build commands to run after install
    type: steps
    default: []
  script:
    description: Script to run.
    type: string
    default: ''

############
# commands #
############
commands:
  setup:
    parameters:
      <<: *default_parameters
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install

  run_script:
    parameters:
      <<: *default_parameters
    steps:
      - setup:
          post_install: << parameters.post_install >>
      - when:
          condition: <<parameters.script>>
          steps:
            - run:
                command: yarn << parameters.script >>
                environment:
                    JEST_JUNIT_OUTPUT_DIR: "test-reports/coverage/clover.xml"

########
# jobs #
########
jobs:
  prepare:
    <<: *defaults
    steps:
      - setup

  build:
    <<: *defaults
    description: Build
    steps:
      - run_script:
          script: type-check
      - store_artifacts:
          path: dist

  test:
    <<: *defaults
    description: Test
    steps:
      - run_script:
          script: jest --ci
      - store_artifacts:
          path: test-reports/coverage
      - store_test_results:
          path: test-reports/coverage

#############
# workflows #
#############
workflows:
  build_and_test:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - test:
          requires:
            - prepare
